added gitops to be deployed using argocd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,31 +155,33 @@ jobs:
   dast-test:
     runs-on: ubuntu-latest
     needs: run-container
-
     steps:
-      - uses: actions/checkout@v4
 
-      - name: Prepare ZAP report
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # Build containers
+      - name: Build containers
+        run: docker compose build
+
+      # Start services
+      - name: Start application stack
+        run: docker compose up -d
+
+      # Wait until backend is ready
+      - name: Wait for backend
         run: |
-          mkdir -p zap-report
-          chmod -R 777 zap-report
-
-      - name: Run ZAP Scan
-        run: |
-          docker run \
-          --network host \
-          -v $(pwd)/zap-report:/zap/wrk/:rw \
-          -t ghcr.io/zaproxy/zaproxy:stable \
-          zap-baseline.py \
-          -t http://localhost:8080 \
-          -r zap-report.html -I
-
-      - name: Upload ZAP report
-        uses: actions/upload-artifact@v4
-        with:
-          name: zap-report
-          path: zap-report
-
+          for i in {1..30}; do
+            if curl -s http://localhost:8080 > /dev/null; then
+              echo "Backend ready"
+              exit 0
+            fi
+            echo "Waiting for backend..."
+            sleep 5
+          done
+          echo "Backend failed to start"
+          docker compose logs backend
+          exit 1
 
 # -----------------------------
 # Image Signing
